### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by freibadschwimmer** [rotdrop/nextcloud-roundcube#4] opened 2023-01-16 22:57 UTC
Hi, thanks a lot for providing this app, it sounds very promising.

Yet, I can't get it working. I tried on 2 different instances on 2 different machines (incl. the one with RC installed), so I think there is something I must be missing on how to set it up, so I think I would benefit from more documentation on how to set it up.

What I did: I downloaded your release (https://github.com/rotdrop/nextcloud-roundcube/releases/download/v1.0.0-rc0/roundcube.tar.gz), and I took the instructions from https://github.com/LeonardoRM/owncloud-roundcube, that is, adding the proxy settings in the Apache vHost, and pointing it to my running RC instance.

It looks like I can add your RC app in NC (25.0.2; PHP8.1; Apache 2.4; RC1.6.0), however, whenever I try to either open the RC app from the NC user interface, or trying to access the NC admin interface, I get an internal server error. The apache log remains clean, but the NC log posts the following error message:

```

{"reqId":"usukKk6rLLlQbmgV1i1d","level":3,"time":"2023-01-16T22:30:07+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"admin@mydomain.com","app":"index","method":"GET","url":"/index.php/settings/admin/overview","message":"Class \"O
CA\\CAFEVDB\\Constants\" not found in file '/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php' line 108","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102
.0","version":"25.0.2.3","exception":{"Exception":"Exception","Message":"Class \"OCA\\CAFEVDB\\Constants\" not found in file '/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php' line 108"
,"Code":0,"Trace":[{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud.kaamoscreation
s.com/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Ro
ute\\Router","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Htt
p/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Class \"OCA\\CAFEVDB\\Constants\" not found","Code":0,"Trace":[{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContai
ner.php","line":108,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","cl
ass":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Util
ity\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer",
"type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":437,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","typ
e":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":89,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"O
C\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Uti
lity/SimpleContainer.php","line":108,"function":"array_map"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Uti
lity\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type
":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/
www/nextcloud.mydomain.com/nextcloud/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextc
loud/lib/private/AppFramework/Utility/SimpleContainer.php","line":57,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/Settings/Manager.php","line":206,"fun
ction":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/Settings/Manager.php","line":335,"function":"getSettings","class":"OC\\Settings\\Manager"
,"type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/lib/private/Settings/Manager.php","line":296,"function":"getPersonalSettings","class":"OC\\Settings\\Manager","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/n
extcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":111,"function":"getPersonalSections","class":"OC\\Settings\\Manager","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/apps/settings/lib/Controller
/CommonSettingsTrait.php","line":62,"function":"formatPersonalSections","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/apps/settings/lib/Controller/Commo
nSettingsTrait.php","line":148,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud.mydomain.com/nextcloud/apps/settings/lib/Controller/
```
Note, I get the same error without the proxy settings. And I also tried with a user as admin, with the same UID/PW as on the mail server (and thus RC login).

**Comment by rotdrop** [comment] 2023-01-17 07:52
Hi, this is simply a bug: I reused code from some other project and did not properly change the namespaces. There will be an update.

Also: I am now publishing the assets in the git repo, so one can also just clone and cross thumbs.

**Comment by rotdrop** [comment] 2023-01-17 08:42
Just uploaded a new pre-release and updated the assets. Maybe you could give it a try ...

**Comment by freibadschwimmer** [comment] 2023-01-17 09:45
Re. administration interface: Now I can open /settings/admin/, but I get an error when opening /settings/admin/roundcube, as follows:

`Installation problem; the required resource \"tpl.adminSettings\" of type \"js\" is not installed on the server, please contact the system administrator!"`

In detail: 

```
{"reqId":"D8wJ0nrLjoR4sMpf76am","level":3,"time":"2023-01-17T09:26:17+00:00","remoteAddr":"my_IP","user":"admin","app":"index","method":"GET","url":"/index.php/settings/admin/roundcube","message":"Installation problem; the required resource \"tpl.adminSettings\" of type \"js\" is not installed on the server, please contact the system administrator!","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","exception":{"Exception":"OCA\\RotDrop\\Toolkit\\Exceptions\\EnduserNotificationException","Message":"Installation problem; the required resource \"tpl.adminSettings\" of type \"js\" is not installed on the server, please contact the system administrator!","Code":0,"Trace":[{"file":"nextcloud/apps/roundcube/lib/Toolkit/Traits/AssetTrait.php","line":118,"function":"getAsset","class":"OCA\\RoundCube\\Service\\AssetService","type":"->"},{"file":"nextcloud/apps/roundcube/lib/Settings/Admin.php","line":77,"function":"getJSAsset","class":"OCA\\RoundCube\\Service\\AssetService","type":"->"},{"file":"nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":129,"function":"getForm","class":"OCA\\RoundCube\\Settings\\Admin","type":"->"},{"file":"nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":149,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"nextcloud/apps/roundcube/lib/Toolkit/Traits/AssetTrait.php","Line":102,"CustomMessage":"--"}}
```

Re App:
When I try to open the app, I get the following error
`"Undefined constant Psr\\Log\\LoggerInterface::ERROR in file 'nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php' line 71"`

In detail: 
```
{"reqId":"ogThp6JD3Dctb3EOAVQU","level":3,"time":"2023-01-17T09:38:13+00:00","remoteAddr":"my_IP","user":"admin","app":"index","method":"GET","url":"/index.php/apps/roundcube/","message":"Undefined constant Psr\\Log\\LoggerInterface::ERROR in file 'nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php' line 71","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","exception":{"Exception":"Exception","Message":"Undefined constant Psr\\Log\\LoggerInterface::ERROR in file 'nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php' line 71","Code":0,"Trace":[{"file":"nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Undefined constant Psr\\Log\\LoggerInterface::ERROR","Code":0,"Trace":[{"file":"nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php","line":98,"function":"mapLogLevels","class":"OCA\\RoundCube\\Service\\Config","type":"->"},{"file":"nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php","line":164,"function":"log","class":"OCA\\RoundCube\\Service\\Config","type":"->"},{"file":"nextcloud/apps/roundcube/lib/Service/Config.php","line":274,"function":"logError","class":"OCA\\RoundCube\\Service\\Config","type":"->"},{"file":"nextcloud/apps/roundcube/lib/Controller/PageController.php","line":94,"function":"emailCredentials","class":"OCA\\RoundCube\\Service\\Config","type":"->"},{"file":"nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\RoundCube\\Controller\\PageController","type":"->"},{"file":"nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},`
```

**Comment by freibadschwimmer** [comment] 2023-01-17 10:25
Sorry, I just noticed that above I posted only the last log entry from trailing the log. Actually, I get 4 error messages in the log when clicking on the App icon in NC:

```
Error: Uninitialized string offset 0 at /var/www/my.domain/nextcloud/apps/roundcube/lib/Service/AuthRoundCube.php#92
    0. /var/www/my.domain/nextcloud/apps/roundcube/lib/Service/AuthRoundCube.php - line 92: 
       OC\Log\ErrorHandler::onError()
    1. <<closure>>
       OCA\RoundCube\Service\AuthRoundCube->__construct()
    2. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 108: 
       ReflectionClass->newInstanceArgs()
    3. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: 
       OC\AppFramework\Utility\SimpleContainer->buildClass()
    4. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133: 
       OC\AppFramework\Utility\SimpleContainer->resolve()
    5. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465: 
       OC\AppFramework\Utility\SimpleContainer->query()
    6. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437: 
       OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
    7. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 89: 
       OC\AppFramework\DependencyInjection\DIContainer->query()
    8. <<closure>>
       OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
    9. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 108: 
       array_map()
    10. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: 
       OC\AppFramework\Utility\SimpleContainer->buildClass()
    11. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133: 
       OC\AppFramework\Utility\SimpleContainer->resolve()
    12. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465: 
       OC\AppFramework\Utility\SimpleContainer->query()
    13. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437: 
       OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
    14. /var/www/my.domain/nextcloud/lib/private/AppFramework/App.php - line 159: 
       OC\AppFramework\DependencyInjection\DIContainer->query()
    15. /var/www/my.domain/nextcloud/lib/private/Route/Router.php - line 298: 
       OC\AppFramework\App::main()
    16. /var/www/my.domain/nextcloud/lib/base.php - line 1047: 
       OC\Route\Router->match()
    17. /var/www/my.domain/nextcloud/index.php - line 36: 
       OC::handleRequest()
```

```

Error: Undefined array key "scheme" at /var/www/my.domain/nextcloud/apps/roundcube/lib/Service/AuthRoundCube.php#100
    0. /var/www/my.domain/nextcloud/apps/roundcube/lib/Service/AuthRoundCube.php - line 100: 
       OC\Log\ErrorHandler::onError()
    1. <<closure>>
       OCA\RoundCube\Service\AuthRoundCube->__construct()
    2. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 108: 
       ReflectionClass->newInstanceArgs()
    3. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: 
       OC\AppFramework\Utility\SimpleContainer->buildClass()
    4. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133: 
       OC\AppFramework\Utility\SimpleContainer->resolve()
    5. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465: 
       OC\AppFramework\Utility\SimpleContainer->query()
    6. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437: 
       OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
    7. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 89: 
       OC\AppFramework\DependencyInjection\DIContainer->query()
    8. <<closure>>
       OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
    9. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 108: 
       array_map()
    10. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: 
       OC\AppFramework\Utility\SimpleContainer->buildClass()
    11. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133: 
       OC\AppFramework\Utility\SimpleContainer->resolve()
    12. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465: 
       OC\AppFramework\Utility\SimpleContainer->query()
    13. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437: 
       OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
    14. /var/www/my.domain/nextcloud/lib/private/AppFramework/App.php - line 159: 
       OC\AppFramework\DependencyInjection\DIContainer->query()
    15. /var/www/my.domain/nextcloud/lib/private/Route/Router.php - line 298: 
       OC\AppFramework\App::main()
    16. /var/www/my.domain/nextcloud/lib/base.php - line 1047: 
       OC\Route\Router->match()
    17. /var/www/my.domain/nextcloud/index.php - line 36: 
       OC::handleRequest()
```
```

Error: Undefined array key "host" at /var/www/my.domain/nextcloud/apps/roundcube/lib/Service/AuthRoundCube.php#101
    0. /var/www/my.domain/nextcloud/apps/roundcube/lib/Service/AuthRoundCube.php - line 101: 
       OC\Log\ErrorHandler::onError()
    1. <<closure>>
       OCA\RoundCube\Service\AuthRoundCube->__construct()
    2. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 108: 
       ReflectionClass->newInstanceArgs()
    3. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: 
       OC\AppFramework\Utility\SimpleContainer->buildClass()
    4. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133: 
       OC\AppFramework\Utility\SimpleContainer->resolve()
    5. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465: 
       OC\AppFramework\Utility\SimpleContainer->query()
    6. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437: 
       OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
    7. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 89: 
       OC\AppFramework\DependencyInjection\DIContainer->query()
    8. <<closure>>
       OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
    9. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 108: 
       array_map()
    10. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: 
       OC\AppFramework\Utility\SimpleContainer->buildClass()
    11. /var/www/my.domain/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133: 
       OC\AppFramework\Utility\SimpleContainer->resolve()
    12. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465: 
       OC\AppFramework\Utility\SimpleContainer->query()
    13. /var/www/my.domain/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437: 
       OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
    14. /var/www/my.domain/nextcloud/lib/private/AppFramework/App.php - line 159: 
       OC\AppFramework\DependencyInjection\DIContainer->query()
    15. /var/www/my.domain/nextcloud/lib/private/Route/Router.php - line 298: 
       OC\AppFramework\App::main()
    16. /var/www/my.domain/nextcloud/lib/base.php - line 1047: 
       OC\Route\Router->match()
    17. /var/www/my.domain/nextcloud/index.php - line 36: 
       OC::handleRequest()
```
```


Exception: Undefined constant Psr\Log\LoggerInterface::ERROR in file '/var/www/my.domain/nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php' line 71
    0. /var/www/my.domain/nextcloud/lib/private/AppFramework/App.php - line 172: 
       OC\AppFramework\Http\Dispatcher->dispatch()
    1. /var/www/my.domain/nextcloud/lib/private/Route/Router.php - line 298: 
       OC\AppFramework\App::main()
    2. /var/www/my.domain/nextcloud/lib/base.php - line 1047: 
       OC\Route\Router->match()
    3. /var/www/my.domain/nextcloud/index.php - line 36: 
       OC::handleRequest()
Caused by Error: Undefined constant Psr\Log\LoggerInterface::ERROR
    0. /var/www/my.domain/nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php - line 98: 
       OCA\RoundCube\Service\Config->mapLogLevels()
    1. /var/www/my.domain/nextcloud/apps/roundcube/lib/Toolkit/Traits/LoggerTrait.php - line 164: 
       OCA\RoundCube\Service\Config->log()
    2. /var/www/my.domain/nextcloud/apps/roundcube/lib/Service/Config.php - line 284: 
       OCA\RoundCube\Service\Config->logError()
    3. /var/www/my.domain/nextcloud/apps/roundcube/lib/Controller/PageController.php - line 94: 
       OCA\RoundCube\Service\Config->emailCredentials()
    4. /var/www/my.domain/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225: 
       OCA\RoundCube\Controller\PageController->index()
    5. /var/www/my.domain/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133: 
       OC\AppFramework\Http\Dispatcher->executeController()
    6. /var/www/my.domain/nextcloud/lib/private/AppFramework/App.php - line 172: 
       OC\AppFramework\Http\Dispatcher->dispatch()
    7. /var/www/my.domain/nextcloud/lib/private/Route/Router.php - line 298: 
       OC\AppFramework\App::main()
    8. /var/www/my.domain/nextcloud/lib/base.php - line 1047: 
       OC\Route\Router->match()
    9. /var/www/my.domain/nextcloud/index.php - line 36: 
       OC::handleRequest()
```

**Comment by rotdrop** [comment] 2023-01-17 10:35
Ok, I think that these are "secondary" errors, i.e. the error reporting is buggy (that's why I did not encounter these errors). I'll have a look, but there will be no updates before tomorrow.

A test-suite would be nice ...

**Comment by freibadschwimmer** [comment] 2023-01-17 10:42
> Ok, I think that these are "secondary" errors, i.e. the error reporting is buggy (that's why I did not encounter these errors).

 I see. I guess that the fact that I can't access the admin settings, and hence not add the roundcube address, will cause (those?) errors.

>  I'll have a look, but there will be no updates before tomorrow.

Good. So I can continue working and not just procrastinate :D

**Comment by freibadschwimmer** [comment] 2023-01-17 22:08
I tried to build the app on my machine, but unfortunately I failed (on 2 machines: Debian Bullseye and Ubuntu 22.04).

This is the error I get when trying to buil the app:
```
touch package-lock.json
make webpack-clean
make[1]: Entering directory '/var/www/html/nextcloud/apps-extra/nextcloud-roundcube-1.0.0-rc1'
Makefile:13: The xpath binary could not be found, falling back to using the CWD as app-name
rm -rf ./js/*
rm -rf ./css/*
make[1]: Leaving directory '/var/www/html/nextcloud/apps-extra/nextcloud-roundcube-1.0.0-rc1'
/usr/bin/npm run dev || rm -f /var/www/html/nextcloud/apps-extra/nextcloud-roundcube-1.0.0-rc1/js/asset-meta.json

> roundcube@1.0.0-rc1 dev
> webpack --node-env development --progress

Building roundcube 1.0.0-rc1 

assets by status 632 KiB [cached] 7 assets
Entrypoint admin-settings = css/admin-settings-da9264f2740b928cf3b3.css js/admin-settings-187f4468bdbbe043c73a.js 2 auxiliary assets
Entrypoint personal-settings = css/personal-settings-da9264f2740b928cf3b3.css js/personal-settings-6d7dea93831685cd51af.js 2 auxiliary assets
Entrypoint app = css/app-f003968cbbded4c9edb6.css js/app-7b1a111db7c6dac485ee.js 2 auxiliary assets
runtime modules 2.87 KiB 13 modules
orphan modules 9.92 KiB [orphan] 7 modules
modules by path ./node_modules/core-js/ 73.4 KiB 104 modules
modules by path ./node_modules/@nextcloud/ 120 KiB 5 modules
modules by path ./src/ 31.2 KiB 4 modules
modules by path ./node_modules/assert/build/ 67.8 KiB 4 modules
modules by path ./node_modules/object-is/*.js 1.14 KiB 4 modules
modules by path ./node_modules/is-nan/*.js 1.2 KiB 4 modules
modules by path ./node_modules/util/ 27.9 KiB 3 modules
modules by path ./node_modules/object-keys/*.js 4.36 KiB 3 modules
modules by path ./style/*.css 3.04 KiB 2 modules
modules by path ./node_modules/call-bind/*.js 1.68 KiB 2 modules
modules by path ./node_modules/function-bind/*.js 1.55 KiB 2 modules
modules by path ./node_modules/has-symbols/*.js 2.13 KiB 2 modules
+ 19 modules

ERROR in [eslint] Failed to load config "@nextcloud" to extend from.
Referenced from: /var/www/html/nextcloud/apps-extra/nextcloud-roundcube-1.0.0-rc1/.eslintrc.js

ERROR in [eslint] Failed to load config "@nextcloud" to extend from.
Referenced from: /var/www/html/nextcloud/apps-extra/nextcloud-roundcube-1.0.0-rc1/.eslintrc.js

webpack 5.75.0 compiled with 2 errors in 10155 ms
/usr/bin/npm run lint

> roundcube@1.0.0-rc1 lint
> eslint --ext .js,.vue src

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the config "@nextcloud" to extend from. Please check that the name of the config is correct.

The config "@nextcloud" was referenced from the config file in "/var/www/html/nextcloud/apps-extra/nextcloud-roundcube-1.0.0-rc1/.eslintrc.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

make: *** [Makefile:162: /var/www/html/nextcloud/apps-extra/nextcloud-roundcube-1.0.0-rc1/js/asset-meta.json] Error 2
```

**Comment by rotdrop** [comment] 2023-01-17 22:42
I fear in order to build the app you will need a full development version even for the NC core.

However, all assets are now contained in the git-repo, so for the time being I suggest you simple clone the git repository.

I just tried to install on some NC 25 without any development things, cloned the roundcube-app repo and then it seems to work at least with the following:

- Roundcube in the same domain as Nextcloud
- Admin settings "Email Address Selection" as "User's Choice"

Then in the personal setting each user can configure the login credentials. Error reporting is flaky, however, if the email password is wrong.

**Comment by rotdrop** [comment] 2023-01-17 22:53
Suppose the eslint thing is caused by a missing @nextcloud/eslint-config in package.json.

**Comment by rotdrop** [comment] 2023-01-19 09:26
Could you please test whether the current state in principle works?

I am sure there are further problems, but the errors discussed are rather about the installation and build infrastructure, and not so much about documentation (which should be improved resp. added, I totally agree with that).

But I would rather invite you to open new issues if the current state can be installed and does at least something useful under certain circumstances.

**Comment by freibadschwimmer** [comment] 2023-01-19 17:05
I just installed rc6, and I confirm that now I can access the settings (both admin as well as for users).
I still need to find my way with the login settings to actually access RC, but I can see from the RC & mail log, that there are login attempts, though I didn't manage to successfully authenticate yet with any of the settings. But I guess in principle the app seems to work, as it connects to RC. :-)

**Comment by nextgen-networks** [comment] 2023-01-27 15:13
> edit: I did manage to login, but I don't see emails (folders appear as empty); when I click on any mail folder, I see a "Server Error (parseerror)" in RC ...

Sounds to me like a [similar issue to](https://github.com/rotdrop/nextcloud-roundcube/issues/6) https://github.com/rotdrop/nextcloud-roundcube/issues/6

**Comment by rotdrop** [comment] 2023-01-28 17:25
> Sounds to me like a [similar issue to](https://github.com/rotdrop/nextcloud-roundcube/issues/6) #6

I have tried the proxy thing by myself and it is a Roundcube configuration problem. See my comments in #6.

**Comment by freibadschwimmer** [comment] 2023-01-28 18:03
Great find.

I can confirm: Adding in the apache nextcloud vhost
```
                SSLProxyEngine on
                ProxyPreserveHost Off
                ProxyPass /roundcube/ https://roundcube.domain.com/
                ProxyPassReverse /roundcube/ https://roundcube.domain.com/
```

and in the roundcube config.ini.php
`$config['request_path'] = '.';`

makes it work also on my installation.
Awesome!

**Comment by rotdrop** [comment] 2023-01-28 18:47
I think we can close this issue now, I have also updated the README.md a bit. For sure there will be more problems, but I would suggest to use new issues for those. Many thanks for testing!

**Closed** 2023-01-28 19:49 UTC
